feat: enhance debug step in audit workflow to check for deny.toml existence

diff --git a/.github/workflows/audit.yml b/.github/workflows/audit.yml
--- a/.github/workflows/audit.yml
+++ b/.github/workflows/audit.yml
@@ -13,8 +13,8 @@ jobs:
       - uses: actions/checkout@v4
       - uses: taiki-e/install-action@cargo-deny
 
-      - name: Debug file exists
-        run: ls R .cargo
-        
+      - name: Debug file existence
+        run: ls -la .cargo && cat .cargo/deny.toml || echo "deny.toml not found"
+
       - name: Scan for vulnerabilities
         run: cargo deny --config .cargo/deny.toml check advisories
